# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
 my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.52833771, 0.6049166 , 0.59768865, 0.8423313 , 0.0199878 ])

In [18]:
np.random.rand(5,5)

array([[0.31189709, 0.13922595, 0.75079223, 0.4274332 , 0.64231959],
       [0.91831407, 0.089875  , 0.42199098, 0.24219224, 0.51195771],
       [0.50599995, 0.7702636 , 0.12186011, 0.07973982, 0.9261205 ],
       [0.60019448, 0.7426294 , 0.23838615, 0.27180089, 0.19175728],
       [0.5576054 , 0.00659236, 0.51163043, 0.57985033, 0.09469547]])

In [20]:
np.random.randn(4,4)

array([[ 0.64087765, -0.45443736,  0.70897285, -1.32135222],
       [ 0.04146795, -1.14647316,  0.5827908 ,  0.22399595],
       [-0.62146911,  0.49844584,  0.56211004, -1.17942145],
       [-0.9766286 , -0.08798614, -0.02238027, -0.03198515]])

In [24]:
np.random.randint(1,100,10)

array([68, 69, 92, 91, 22, 52, 56, 10, 45, 74])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([45, 10, 13,  8, 45, 15, 31, 16, 22, 49])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

49

In [31]:
ranarr.min()

8

In [32]:
ranarr

array([45, 10, 13,  8, 45, 15, 31, 16, 22, 49])

In [33]:
ranarr.argmax()

9

In [34]:
ranarr.argmin()

3

In [35]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int32')